apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ecom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-ecom-app
  template:
    metadata:
      labels:
        app: java-ecom-app
    spec:
      containers:
      - name: java-ecom-app
        image: leocrita/java-ecom-app:latest
        ports:
        - containerPort: 8080

